version: "3.9"
name: Discord Bot Container

services:
  app:
    image: alfiephillips/discord-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
